### ISSUE TITLE
Outdated Alpine version

### ISSUE THREAD

**Issue by joe-bowman** [smartcontractkit/external-adapters-js#1015]
Your Dockerfile uses node:14-alpine as it's base image, which currently uses Alpine 3.11. This particular version is EOL on 1 Nov, and is three versions behind the current stable version of Alpine.

Unfortunately, the node docker image maintainer feels that they should use the oldest in-life version of Alpine, which I find to be an odd stance.

I would recommend we pin to the latest version of Alpine (node:14-alpine3.14 currently, which we have been using for self-compiled images for months) and consciously update this (every 6 months) to the most recent version, for security reasons.

**Comment by boxhock** [comment]
Hey Joe. We'll be updating to `node:17-alpine` in #1219, which will be included in the next release. This will be using Alpine 3.15.

To your point about the node image using the oldest in-life version of Alpine, it looks to me like `node:14-alpine` is also currently using Alpine 3.15: https://github.com/nodejs/docker-node/blob/main/14/alpine3.15/Dockerfile. Prior to this, it seems like it was using Alpine 3.12. Does this seem correct?

We'll keep an eye out for this, so thanks for bringing it up! For now, it looks like we can get away without pinning the Alpine version, but we'll keep this in mind going forward.

I'll be closing this issue once #1219 is merged.

**Comment by joe-bowman** [comment]
Prior to 3249d350bda58bbb83a5b18a2bf14b46a8b49fc7 (committed on 4th Nov) node:14-alpine was using 3.11. 

(see: https://github.com/nodejs/docker-node/commit/3249d350bda58bbb83a5b18a2bf14b46a8b49fc7#diff-2b39d33506bc7a34cef4b9ebf4cf8b1e3a5532f2131ceb37011b94261cec5f8c).

Unfortunately, when I last tested in late December, all the Chainlink-built Docker images were still based on 3.11, two months after it has been EOL'd. This isn't really acceptable for production software.

Thankfully the move to node17 and 3.15 should keep us good for the next while! thank you for looking into this!

**Comment by boxhock** [comment]
Got it, and I agree - we have higher expectations for the software we ship. Thanks again for raising this. Closing this now as #1219 is merged and will be included in the release next week, but we'll monitor this going forward.

**Comment by joe-bowman** [comment]
Thank you. Appreciated.
