### ISSUE TITLE
(continued) Improve error logging within our EA framework 

### ISSUE THREAD

**Issue by bryanjowers** [smartcontractkit/external-adapters-js#1051]
update bootstrap to ensure error throw causes withlogger to log rather than native logging

Justin says to discuss with him

**Comment by justinkaseman** [comment]
Some more details:

Our EAs have a middleware called `withLogger` that should be the standarized location that errors are caught and formatted.
https://github.com/smartcontractkit/external-adapters-js/blob/develop/packages/core/bootstrap/src/index.ts#L82
This will ensure consistency behind error logging.

Any place that there is a `catch` block in the code base should re-throw the error to be caught by `withLogger`.
These catch blocks could still useful if we want to add more data to the error.

**Comment by justinkaseman** [comment]
I just combed through all of our catch blocks and I only see one place that this might be relevant.
https://github.com/smartcontractkit/external-adapters-js/blob/develop/packages/core/bootstrap/src/lib/external-adapter/validator.ts#L146
We could throw here intsead of log.

Everywhere else seems to re-throw the error as we want.
