### ISSUE TITLE
Bring in external Anyblock VWAP endpoint  

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#1105]
Our current Anyblock adapter has a VWAP endpoint that performs its own VWAP calculation from Ethereum events.

Anyblock also provides an endpoint to do this.
It can be seen on this EA that they have build:
https://github.com/anyblockanalytics/chainlink-oracle-market-adapter

We should bring this same functionality into our adapter.
The `vwap` endpoint name should be added to this new endpoint and removed from the previous one.
The previous one could be renamed to `calculate-vwap`.

**Comment by austinborn** [comment]
Needs to support `from/to` input params
