### ISSUE TITLE
Type safe EAs

### ISSUE THREAD

**Issue by bryanjowers** [smartcontractkit/external-adapters-js#1310]
100% of EA bootstrap is typed.

The goal is to be able to turn on the "noAny" and "noImplicitAny" settings in TypeScript.

- [ ] burst-limit
- [ ] cache
- [ ] cache-warmer
- [ ] config
- [ ] external-adapter
- [ ] metrics
- [ ] provider-limits
- [ ] rate-limit
- [ ] store
- [ ] ws
- [ ] server
- [ ] utils

**Comment by austinborn** [comment]
Once noAny is enabled, please remove the lines indicated by //TODO Please remove these once "no any" strict typing is enabled in validator.ts

**Comment by justinkaseman** [comment]
Completed in https://github.com/smartcontractkit/external-adapters-js/pull/1778
