### ISSUE TITLE
InputParameters' "default" value used when an invalid "options" value is provided

### ISSUE THREAD

**Issue by jnapprogs** [smartcontractkit/external-adapters-js#1531]
Hi all!  I was wondering if I can get some insight for the behavior of the `default` property for the `InputParameters` type.  I have an input parameter initialized as follows:

```typescript
const inputParams = {
  item: {
    aliases: ['item'],
    required: false,
    type: 'string',
    default: 'first',
    options: ['first', 'second', 'third']
  }
}
```

If I do not provide a value for the `item` parameter, then it defaults to `first`.  If I specify any of the values in the `options` property, then that value is used instead; however, if I was to provide a value that isn't part of the `options` property, say `this should break`, it defaults to `first`.  Even though a default value has been specified, I assumed that the adapter would throw an error as a value has been provided that isn't part of the `options` property.  As an external user, if I wanted a `fourth` item, I would keep receiving back the `first` item.

With that, is the `default` value intended to be used in the event a user does not provide a value, or does it also play a dual role in being the default value if a wrong `options` value is provided?

**Comment by austinborn** [comment]
Hi @jnapprogs, thank you for pointing this out. I don't have an immediate answer for you since this does not appear to be due to the `Validator` class itself, but I would expect proper behavior to be to throw an error as well. We have added it to the bug queue and will prioritize accordingly. Happy to give further assistance if you would like to debug as well.

**Comment by jnapprogs** [comment]
@austinborn , thanks for the response!  I should be fine on the debugging front, but will definitely reach out in the event I have to 🚀

**Comment by austinborn** [comment]
@jnapprogs I believe this should resolve the issues you were seeing. With this change, an input that's not a part of the `options` array will return an error instead of silently defaulting to the default value.

**Comment by jnapprogs** [comment]
Awesome!  Thanks for the info!

**Comment by austinborn** [comment]
> Awesome! Thanks for the info!

Of course! Happy to get a quick turnaround on this one.
