### ISSUE TITLE
Improve documentation on PoR & composite adapters in general

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#168]
Currently, it's not straightforward for node operators to understand quickly how to build & run composite adapters like Proof of Reserve. Composite adapters have underlying adapters they use of which each has some kind of configuration and/or defaults. All of this info is currently obscure and hard to get to.

As suggested by @tyrion70:

> Ideally the README has everything needed for a node operator to get it started together with the jobspecs of course

**Comment by boxhock** [comment]
Closing this as documentation has been improved with Notion docs and we have strengthened our READMEs
