### ISSUE TITLE
Sequences processing semantics [Draft]

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#175]
Some of our adapters like the PoR bitcoin indexer adapters process sequenced data.

Adapters that process sequences should only change items that they know how to process. If they don’t have the ability to process them they should add a warning. Maybe the next adapter in the chain will have the know-how to process those items and possibly remove the warning.

If they have the ability to process the item, but the item is found to be invalid, the error should be thrown as there is no way to continue processing this sequence. For example, if we have an adapter that processes `bitcoin/mainnet` addresses. That adapter should add warnings for all `bitcoin/testnet` and `ethereum/mainnet` addresses. But if it finds an invalid `bitcoin/mainnet` address, then it throws an error!

We can additionally add a `strict` configuration flag, which we can use to configure the sequence processing adapter with: “No warnings, all errors.” Or in other words, you need to be able to process everything or nothing.

TODO:

- [ ] How sequence processing semantic should work
- [ ] How we should be able to chain different adapters with different processing abilities
- [ ] How error handling should work
- [ ] How can we extract this in a framework to easily add sequence processing abilities to an adapter

**Comment by boxhock** [comment]
Story created
