### ISSUE TITLE
Improve adapter input validation and documentation

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#176]
This idea started [here](https://github.com/smartcontractkit/gauntlet/pull/363#issuecomment-737204518) by @yosriady.

As validation is also a big part of external-adapters-js, which has a simple [Validator](https://github.com/smartcontractkit/external-adapters-js/blob/master/external-adapter/src/validator.js) we currently use, it would be great if we could combine our efforts here and define a simple validation utility that we would use for both.

I like the idea of defining a declarative validation strategy, one that we could also use to add extra documentation to external adapters. Either printing it to logs or adding a special endpoint that would return the input schema for documentation and debug purposes. But just reading it from source code as-is would be beneficial for someone trying to deploy and use those adapters. Better and more specific error messages would also bring a much improved UX.

If we enable to easily write custom validation functions, more would be written, which would also further improve code safety.

**Comment by yosriady** [comment]
:+1: to this

**Comment by boxhock** [comment]
Improvements have been made by @austinborn
