### ISSUE TITLE
Export EA Masterlist to Airtable when Consume Changeset PR is merged

### ISSUE THREAD

**Issue by eddiejhong** [smartcontractkit/external-adapters-js#1803]
EA Masterlist is now generated automatically with each Consume Changeset PR and merged in with the rest of the version updates. In a post-merge operation, export the updated masterlist data to an external document (ideally Airtable for visibility with NOPs). Requires investigation into Airtable APIs and getting proper API keys for those.

Use the [Airtable API](https://support.airtable.com/hc/en-us/articles/203313985-Public-REST-API) to perform relevant operations to update the reference Airtable doc. If it's straightforward to create new docs too or a directory of docs, you can try creating a set of versioned tables for each external-adapters-js version release, and then have a separate latest version for standard use.

**Comment by karen-stepanyan** [comment]
Airtables API is very limited and it doesn't allow to programmatically create new tables so versioned masterlists can't be done in this way.
