### ISSUE TITLE
Etherscan adapter: missing new fields of Get Gas Oracle

### ISSUE THREAD

**Issue by aelmanaa** [smartcontractkit/external-adapters-js#1819]
Hello,

the [Get Gas Oracle](https://docs.etherscan.io/api-endpoints/gas-tracker#get-gas-oracle) has new fields `suggestBaseFee` and `gasUsedRatio` which are missing in the adapter.

Also, I've got a suggestion for the default behavior: Maybe we should return all the fields instead of returning only the fast one

https://github.com/smartcontractkit/external-adapters-js/blob/86ae9787d42645fe6258364812039cc5dc44f6d1/packages/sources/etherscan/src/endpoint/gasprice.ts#L52

**Comment by justinkaseman** [comment]
Hey @aelmanaa, finally getting around to responding to this - thanks for opening it.

We will update the response interface for those new types.

As for the default behavior, the EA usually wants to respond with a single value, unless the feeds job spec uses multi-word response.
