### ISSUE TITLE
'API will be rate limited without an API key.' logged for adapters that don't require an API_KEY

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#182]

**Comment by ebarakos** [comment]
Could be omitted as well maybe? Might not be the case even for some of those that require key.

**Comment by GMSteuart** [comment]
@krebernisak If this is still an issue, can you provide error output and a code sample for what you are talking about?

**Comment by boxhock** [comment]
This is no longer an issue
