### ISSUE TITLE
Airtable EA Master List updates existing rows properly

### ISSUE THREAD

**Issue by eddiejhong** [smartcontractkit/external-adapters-js#1874]
**Description**
Debug airtable master list pipeline to ensure existing rows can be updated with new information. Based on my testing this part of the feature does not work properly.

**Estimate**
1 day

**Stakeholders**
Product integrations team (as developer)
Node operators (as customer)

**Acceptance criteria**
Airtable EA Master List can update through the gh actions without manual intervention to delete the rows first

**Comment by austinborn** [comment]
Actually I believe we can close this one. I didn't realize the update script skips EAs where the `version` hasn't changed, so it looked like they weren't updating when I changed a property. False alarm.
