### ISSUE TITLE
Log adapter errors

### ISSUE THREAD

**Issue by RodrigoAD** [smartcontractkit/external-adapters-js#204]
Currently if there is some internal error, it just get notified to the client with a `500` without logging anything. Logging this would be really helpful for debugging and recognize faster possible problems in production adapters

**Comment by justinkaseman** [comment]
I took a glance at this while working on the log size, do you have some steps to reproduce?

For example when I run `amberdata` without an API key the client gets:
```JSON
{"jobRunID":"1","status":"errored","statusCode":500,"error":{"name":"AdapterError","message":"Invalid value \"undefined\" for header \"x-api-key\""}}
```
and the node operator sees:
```JSON
{"message":"Could not reach endpoint: \"Invalid value \\\"undefined\\\" for header \\\"x-api-key\\\"\"","level":"error","instanceId":"68b86ad1-c120-47f2-a004-5245a3dff690","timestamp":"2021-01-07T18:15:26.890Z"}
```
---

Giving an invalid `Requester.validateResultNumber` path gives the following to the client:
```JSON
{"jobRunID":"1","status":"errored","statusCode":500,"error":{"name":"AdapterError","message":"Result could not be found in path"}}
```
and to the node operator:
```JSON
{"message":"Result could not be found in path","level":"error","instanceId":"bad3f72e-ff7b-4853-896f-354e4bd03e2d","timestamp":"2021-01-07T18:26:39.447Z"}
```

which also seem fine to me.

**Comment by justinkaseman** [comment]
Following up - reproduced this while acceptance testing the Proof of Reserves composite adapter.

**Comment by RodrigoAD** [comment]
Those errors seem that are caught by the Requester. If you introduce any error, ie a `throw` inside the adapter execute function, the adapter will fail without notifying anything.

**Comment by boxhock** [comment]
This should be covered by separate stories in Shortcut now
