### ISSUE TITLE
Circular dependency between bootstrap and external-adapter

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#205]
We currently use [shorthand ambient modules](https://www.typescriptlang.org/docs/handbook/modules.html#shorthand-ambient-modules) in our @chainlink/types:

```
declare module '@chainlink/external-adapter
declare module '@chainlink/ea-bootstrap
```

These stifle types by setting every export to be `any`, defeating our type safety.
We are unable to remove them because of a circular dependency between these two packages.

https://github.com/smartcontractkit/external-adapters-js/pull/184/commits/b847ff2816ecb4573a17092c389194103f2a912a

Is a band-aid to allow CI to run with this issue. It should be removed.

**Comment by GMSteuart** [comment]
@justinkaseman did PR #359 close this issue or no?

**Comment by boxhock** [comment]
Assuming this is fixed, so closing. Feel free to re-open if that's not the case.
