### ISSUE TITLE
 Chainlink node's run status page does not propagate errors correctly for failures.

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#210]
Working on [Agoric adapter implementation surfaced an issue](https://github.com/smartcontractkit/external-adapters-js/pull/114/files#r529855821) with error handling that should need further investigation.

**Comment by michaelfig** [comment]
See #204 which describes this error.

**Comment by boxhock** [comment]
The linked issue should be resolved. If there are any more issues with the Chainlink node's run page, it should be opened in the https://github.com/smartcontractkit/chainlink repo
