### ISSUE TITLE
Config improvements

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#217]
### Description

Re-usable Configs were recently added to reduce shared code between EAs. This was a simple first-step and should be improved upon.

There was concern about them being too static. A generic type was added to ExecuteFactory to allow many Config types. This concern should be given more thought for the future.

These configurations should be extendable and be able to come from a variety of sources (URL params, ENV variables, argument to factory, ect.)

The compostability of these configurations in their current form should be verified.

**Comment by justinkaseman** [comment]
The introduction of cycling through API keys requires an API key to be set. Some data providers do not need API keys. `defaultConfig` needs to be told if an API key is needed. One solution might be to give it a Config object of defaults. Anything not given is filled from framework defaults.

**Comment by boxhock** [comment]
Is this resolved or do we have a Shortcut story for this?

**Comment by justinkaseman** [comment]
> Is this resolved or do we have a Shortcut story for this?

Yeah I believe every part of this is resolved.

**Comment by justinkaseman** [comment]
Closing as complete
