### ISSUE TITLE
Improve support for multiple keys in API_KEY env variable

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#219]
There are still some places in the codebase that use `util.getRequiredEnv('API_KEY')` instead of `getRandomRequiredEnv` function. 

We'll need to update those and also make sure that we add an ability to specifically require the API key when using the `Requester.getDefaultConfig` function, as some adapters use it but don't require an API key set, for example the `dydx-stark` adapter.

**Comment by boxhock** [comment]
Story created in Shortcut. Requiring an API key in `Requester.getDefaultConfig` should now be possible.
