### ISSUE TITLE
Improve test-helper behavior input

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#223]
We should be able to generate this list from `COIN_KEYS` & `CHAIN_KEYS`.

Nothing critical for now, please open an issue to track it and fix later.

_Originally posted by @krebernisak in https://github.com/smartcontractkit/external-adapters-js/pull/184#discussion_r555902529_

**Comment by boxhock** [comment]
@justinkaseman do you have more details, or can we close this?

**Comment by justinkaseman** [comment]
IIRC it was about dynamically generating tests for PoR based on the `COIN_KEYS` and `CHAIN_KEYS` enums. We can close this as stale.
