### ISSUE TITLE
Adapters should automatically export their name

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#244]
The discussion about this started [here](https://github.com/smartcontractkit/external-adapters-js/pull/221#discussion_r558107864).

This was first used as an ENV prefix to avoid naming collisions when using two or more adapters in the same env. So for now it was a simple hardcoded uppercase string.

What we should do now to make this more robust is this:

- Import the `name` from `package.json`, remove the `-adapter` suffix, and export that as NAME.
- Create a `toEnvName` util function that will map it to a safe string to use as ENV prefix to avoid naming collisions.

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit.

**Comment by GMSteuart** [comment]
Has consideration gone into reading the adapter name from the package.json file that can be found in all external adapter folders?

**Comment by boxhock** [comment]
Shortcut story created
