### ISSUE TITLE
Make e2e integration tests more usable by injecting secrets

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#245]
Integration tests, like they are currently set up, are not too usable. We would like to start integration tests for all adapters at once, but how do we then inject a different API key to each one?

One possible solution would be to have a `secrets.json` configured with all secrets required for integration tests. Then every test can read from there.

For CI runs we could have an encrypted `secrets.json.gpg` file that gets decrypted and provided to the test suite. Documentation on this workflow can be found [here](https://docs.github.com/en/actions/reference/encrypted-secrets#limits-for-secrets).

_Originally posted by @krebernisak in https://github.com/smartcontractkit/external-adapters-js/pull/218#discussion_r559507417_

**Comment by GMSteuart** [comment]
@krebernisak has consideration gone into a way of generalizing the creation of mock api requests to be used before working on api key integration development?
