### ISSUE TITLE
Make integration tests more usable by mocking HTTP requests

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#247]
Instead of using `Requester` static functions to make HTTP requests, we would like to rewrite this functionality as an HTTP module object that gets injected into the adapter, and as such can be easily mocked in tests.

This will enable easier tests, better test coverage, and running more tests in the CI environment, increasing the overall codebase safety.

**Comment by boxhock** [comment]
Integration tests are now using mocks
