### ISSUE TITLE
Improve EA error handling

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#258]
My thoughts are that we should handle most/all of errors, output them with correct status codes and appropriate messages. We have work to do here.

Internal errors should be caught, mapped to a HTTP 500 status code and construct an appropriate message. Something like `Internal Server Error: ${error.name}`. Then if we are in dev env (NODE_ENV=development) or some other `verbose/debug` flag is set, we dump the whole internal error on the output, as an underlying `cause` to be investigated.

_Originally posted by @krebernisak in https://github.com/smartcontractkit/external-adapters-js/issues/212#issuecomment-759739934_

**Comment by boxhock** [comment]
@justinkaseman do you feel like we have Shortcut stories that sufficiently cover this issue?

**Comment by justinkaseman** [comment]
Yes, shout out to everyone who has put work into this. Matt, Andre, & Karen especially.
