### ISSUE TITLE
API keys from Config

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#267]
There are a couple places in the codebase where API keys are accessing from within an endpoint's code. These instead need to be handled in `makeConfig`. 

This change will interfere with validation tests. These tests currently do not have any API keys. They could be passed into tests through the Config.

_Originally posted by @justinkaseman in https://github.com/smartcontractkit/external-adapters-js/pull/226#discussion_r562270082_

**Comment by boxhock** [comment]
@justinkaseman do you know if this is still an issue?

**Comment by justinkaseman** [comment]
> @justinkaseman do you know if this is still an issue?

The original comment that opened this issue is resolved. Closing.
