### ISSUE TITLE
Blockcypher request rate limiting 

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#280]
### Description
The Blockcypher balance adapter is blocked because their rate limit per second, even on their most premium plan, will not work with wbtc's ~30 custodial wallet requests.

One solution could be to allow a new environment variable for `RATE_LIMIT` = `10`, where the number given will be the number of requests sent per second.

This would unlock the `wbtc` `proof-of-reserves` adapter and allow node operators to use a cheaper plan.

---

The above has been given a naive solution, but a more re-usable function could be added to utils.

### References
#276

**Comment by boxhock** [comment]
Closing this as we're not focusing on adding support for Blockcypher for PoR
