### ISSUE TITLE
Investigate test timeouts

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#294]
I believe we need a timeout to give error tests time to retry. This does need more investigation though.

The problem I have noticed is that different APIs take different amount of times to timeout. In the example of 1forge I had to increase it this much to pass, where as other adapters could take lower amounts (usually 3000 to allow three 1 second retries).

_Originally posted by @justinkaseman in https://github.com/smartcontractkit/external-adapters-js/pull/226#discussion_r565698362_

**Comment by GMSteuart** [comment]
@justinkaseman can you provide any error output of what you are talking about? There are Jest functions that have a 5s default timeout.
