### ISSUE TITLE
Refactor getting environment variables

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#299]
> Maybe we could avoid some duplication with the other method? Like passing a boolean value e.g `= (name: string, required = true, delimiter = ',', prefix = '')` and use `util.getRandomEnv('API_KEY')` in all places.
> 
> Then we can call `util.getRandomEnv('API_KEY', false)` in places that we don't want the var to be required.
> 
> Or something similar.

_Originally posted by @ebarakos in https://github.com/smartcontractkit/external-adapters-js/pull/226#discussion_r570260831_

**Comment by ebarakos** [comment]
Tackling this in [`08a5e4a` (#293)](https://github.com/smartcontractkit/external-adapters-js/pull/293/commits/08a5e4ad90d3a9f71fb3ae63330968c8da396a18)

**Comment by GMSteuart** [comment]
@justinkaseman any reason not to use [dotenv](https://github.com/motdotla/dotenv)

**Comment by boxhock** [comment]
@justinkaseman is this still relevant?

**Comment by alejoberardino** [comment]
I do think this would be a good change to make, there are many libraries that handle getting env vars and additionally defining a schema to validate them

**Comment by justinkaseman** [comment]
Closing in favor of EAv3
