### ISSUE TITLE
Testing patterns for mocking blockchains

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#321]
We need better tooling around using blockchains in our test environment

> Spent some time to make it working with `before`, but async initialization does not work on `describe`/`context`(https://github.com/mochajs/mocha/issues/2975).
>
> Async calls could be resolved inside `it` though.

_Originally posted by @ebarakos in https://github.com/smartcontractkit/external-adapters-js/pull/290#r576315075_

**Comment by GMSteuart** [comment]
Can you provide error output and a code sample for what you are talking about?
