### ISSUE TITLE
Balance endpoints incorrectly parse units

### ISSUE THREAD

**Issue by justinkaseman** [smartcontractkit/external-adapters-js#329]
### Description
Balance endpoints originally were created for Bitcoin Proof of Reserves.
The External Adapters were engineered to be able to handle more than just Bitcoin.
In some cases the balance units needs to be converted.

A [recent PR](https://github.com/smartcontractkit/external-adapters-js/commit/73d22c536707548a42b24825e87803f178466743) hard coded conversion to BTC, when it could be multiple currencies.
A better utility function should be created or support for other currencies should be disabled.

This issue can be re-created by running `yarn test` in `cryptoapis` adapter.
Ethereum chains will throw this error trying to convert the units:
```
Error: fractional component exceeds decimals (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.0.14)
```

**Comment by boxhock** [comment]
As far as I can tell, this is no longer an issue
