### ISSUE TITLE
Coingecko EA not working properly with the cache

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/external-adapters-js#356]
Typically, when a job hits the api directly, the response looks like this:
```json
{"jobRunID":"1","result":0.02570336,"statusCode":200,"data":{"result":0.02570336}}
```
And when it hits the cache, a successful response looks something like this:
```
{"result":0.025649,"maxAge":60000,"statusCode":200,"data":{"status":200,"title":"OK","description":"Successful request","payload":{"timestamp":1615461840000,"pair":"bal_eth","price":"0.025649","volume":"0.95"},"result":0.025649}}
```

For coingecko, we get this:
```
{"maxAge":60000,"statusCode":200,"data":{"result":0.025649}}
```

The jobspecs are looking for a `result` field at the top level. Can we please add it so that all caches send the `result` to the top level?

**Comment by boxhock** [comment]
This issue is already resolved in the `develop` branch. Could you please check if this is still a problem there?

**Comment by PatrickAlphaC** [comment]
all set, thanks
