### ISSUE TITLE
Websockets - Redux action status

### ISSUE THREAD

**Issue by RodrigoAD** [smartcontractkit/external-adapters-js#470]
A single async action should continue with a minimum of 2 actions, with 3 actions being the norm for error handling. E.g.

For unsubscribing, we would have the following set of actions:
```
WS/UNSUBSCRIBE_REQUESTED
WS/UNSUBSCRIBE_SUCCESSFUL
WS/UNSUBSCRIBE_FAILED
```
To reduce the amount of boilerplate this generates, we can use the createSlice helper function provided by redux toolkit which automatically creates actions based on the configured reducer keys

**Comment by justinkaseman** [comment]
Closing as this will be made obsolete by EAv3
