### ISSUE TITLE
[FEATURE] Serverless Framework and OpenWhisk Integration

### ISSUE THREAD

**Issue by leovigna** [smartcontractkit/external-adapters-js#56]
OpenWhisk is an opensource FaaS solution that can easily be deployed on Kubernetes. I'd like to make it possible to deploy all of the adapters on OpenWhisk with the help of Serverless Framework.

This way, deployment of new adapters can be as easy as `sls deploy`

**Comment by boxhock** [comment]
Hey, since we've pivoted towards Docker support only, it seems like this issue has become irrelevant as we wouldn't be able to support other serverless frameworks. I'll close this issue, but feel free to re-open if you feel like this is still relevant.
