### ISSUE TITLE
 cache.gold Proof of Reserves EA

### ISSUE THREAD

**Issue by bryanjowers** [smartcontractkit/external-adapters-js#672]
This is a new EA that queries a single endpoint and returns the value for grams of gold locked.

**Blockchain:** Ethereum

**API endpoint**  (unauthenticated): [https://contract.cache.gold/api/lockedGold](https://contract.cache.gold/api/lockedGold)

GET request returns the following JSON payload: {"grams_locked":"62293.77000000"}

Input: this endpoint does not require any fields to be passed on input
Output: We want this grams_locked value returned as output from the adapter.

**Comment by boxhock** [comment]
Closing as it seems this EA has been created already
