### ISSUE TITLE
Wootrade

### ISSUE THREAD

**Issue by bryanjowers** [smartcontractkit/external-adapters-js#691]
Wootrade Network is a market maker building deep liquidity pools. They want us to build feeds with their data only to be used for their private pools on polygon. 

**3 Pairs**: 
* BTC/USDT
* ETH/USDT
* MATIC/USDT

These are the first 3 pairs we want to support, but we should build flexibly so that any pair could be supported

We will use their websocket v2 API and the bbo (unauthenticated API): https://kronosresearch.github.io/wootrade-documents/#websocket-api-v2

Websocket endpoint: wss://wss.woo.network/ws/stream/bbo

**Comment by bryanjowers** [comment]
The endpoint/API does not provide a `price` directly. Instead they provide values that we can use to calculate the `price`. 

How to calculate the output price: 
Using the `bbo` endpoint: https://kronosresearch.github.io/wootrade-documents/#bbo provides 2 values: a `bid` and `ask` price. Wootrade wants us to calculate an average of these 2 values for the pair

**Comment by boxhock** [comment]
Looks like we added support for this adapter
