### ISSUE TITLE
New EA: Etherscan - enabled for fast gasprice

### ISSUE THREAD

**Issue by bryanjowers** [smartcontractkit/external-adapters-js#753]
This task is to add a new EA that returns the latest FastGasPrice

We have existing gasprice EAs that can be used as examples: 
1. https://github.com/smartcontractkit/external-adapters-js/tree/develop/packages/sources/ethgasstation
2. https://github.com/smartcontractkit/external-adapters-js/tree/develop/packages/sources/etherchain

## Endpoint(s)

[https://api.etherscan.io/api?module=gastracker&action=gasoracle&apikey=WJDKF9SK5R5JQZWMK6U2E7AHZDN8JGHE2E](https://api.etherscan.io/api?module=gastracker&action=gasoracle&apikey=WJDKF9SK5R5JQZWMK6U2E7AHZDN8JGHE2E)

    *Response example:*

    {"status":"1","message":"OK","result":{"LastBlock":"12966449","SafeGasPrice":"141","ProposeGasPrice":"161","FastGasPrice":"**294**"}}

    Value to capture (in bold above): "FastGasPrice":"**294**"

 Bryan to provide test API credentials

**Comment by austinborn** [comment]
Complete: https://github.com/smartcontractkit/external-adapters-js/pull/830
