### ISSUE TITLE
New EA: Upvest - enabled for fast gasprice

### ISSUE THREAD

**Issue by bryanjowers** [smartcontractkit/external-adapters-js#754]
This task is to add a new EA that returns the latest FastGasPrice

We have existing gasprice EAs that can be used as examples: 
1. https://github.com/smartcontractkit/external-adapters-js/tree/develop/packages/sources/ethgasstation
2. https://github.com/smartcontractkit/external-adapters-js/tree/develop/packages/sources/etherchain

## Endpoint(s)

[https://fees.upvest.co/estimate_eth_fees](https://fees.upvest.co/estimate_eth_fees)

    Response example:

    {"success":true,"updated":"2021-08-05T18:01:00.169Z","estimates":{"fastest":212.833,"fast":191.333,"medium":159,"slow":148.067}}

Value to capture: "fast":191.333

No API credentials needed

**Comment by austinborn** [comment]
Complete: https://github.com/smartcontractkit/external-adapters-js/pull/833
