### ISSUE TITLE
New EA: EthGasWatch - enabled for fast gasprice

### ISSUE THREAD

**Issue by bryanjowers** [smartcontractkit/external-adapters-js#756]
This task is to add a new EA that returns the latest FastGasPrice

We have existing gasprice EAs that can be used as examples: 
1. https://github.com/smartcontractkit/external-adapters-js/tree/develop/packages/sources/ethgasstation
2. https://github.com/smartcontractkit/external-adapters-js/tree/develop/packages/sources/etherchain

Endpoint: [https://ethgas.watch/api/gas](https://ethgas.watch/api/gas)

Open API - no API key required, no subscription required

## Endpoint(s)

[https://ethgas.watch/api/gas](https://ethgas.watch/api/gas)

**Response example:**

    
    {"slow":{"gwei":285,"usd":16.75},"normal":{"gwei":323,"usd":18.98},"fast":{"gwei":355,"usd":20.86},"instant":{"gwei":368,"usd":21.63},"ethPrice":2798.63,"lastUpdated":1628185830166,"sources":[{"name":"Etherscan","source":"https://etherscan.io/gastracker","fast":355,"standard":328,"slow":306,"lastBlock":12966365},{"name":"Etherchain","source":"https://etherchain.org/tools/gasPriceOracle","instant":367,"fast":292,"standard":152,"slow":102,"lastUpdate":1628185829902},{"name":"GAS Now","source":"https://www.gasnow.org/","instant":141,"fast":73,"standard":64,"slow":64,"lastUpdate":1628185827415},{"name":"Gas station","source":"https://ethgasstation.info/","instant":428,"fast":387,"standard":323,"slow":285,"lastBlock":12966385},{"name":"MyCrypto","source":"https://gas.mycryptoapi.com/","instant":368,"fast":257,"standard":138,"slow":96,"lastBlock":12966394},{"name":"POA Network","source":"https://gasprice.poa.network/","instant":428,"fast":387,"standard":323,"slow":285,"lastBlock":12966385},{"name":"Upvest","source":"https://doc.upvest.co/reference#ethereum-fees","instant":364,"fast":335,"standard":278,"slow":234,"lastUpdate":1628185830115}]}
    

Value to capture from response : "fast":{"gwei":355

**Comment by austinborn** [comment]
Complete: https://github.com/smartcontractkit/external-adapters-js/pull/831
